package(default_visibility = ["//visibility:public"])

py_library(
    name = 'global_te',
    srcs = ['global_te.py'],
    deps = [
        "//proto:topology_proto",
        "//proto:traffic_proto",
        "//proto:te_solution_proto",
        '//topology:topology',
        '//traffic:traffic',
    ],
)
