package(default_visibility = ["//visibility:public"])

py_library(
    name = 'common',
    srcs = ['common.py'],
    deps = [
    ],
)

py_library(
    name = 'flags',
    srcs = ['flags.py'],
    deps = [
    ],
)
