# Site settings
title: FabricEval
email: shuoshuc@cs.cmu.edu
description: >
  A traffic engineering evaluation framework.
lang: en-US

baseurl: "/FabricEval" # the subpath of your site, e.g. /blog/
url: https://shuoshuc.github.io/FabricEval # the base hostname & protocol for your site
git_address: https://github.com/shuoshuc/FabricEval
git_edit_address: https://github.com/shuoshuc/FabricEval/tree/website

# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: simplex # paper cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - vendor
timezone: America/New_York
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: team

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /team/
    output: true
